name: SkyAlchemist
version: '1.0-SNAPSHOT'
main: org.k0rv1nes.skyAlchemist.AlchemistPlugin
api-version: '1.18'
depend: [PlayerPoints]
description: Плагин для скрещивания эффектов зелий за определенную цену.
author: k0rv1nes
commands:
  alchemist:
    description: Открывает меню алхимика или перезагружает конфигурацию.
    usage: /alchemist [reload]
    permission: alchemist.use
    permission-message: "&cУ вас нет прав для использования этой команды."
permissions:
  alchemist.use:
    description: Разрешение для использования команды /alchemist.
    default: true
  alchemist.reload:
    description: Разрешение для перезагрузки конфигурации плагина.
    default: op
